remove travis

diff --git a/.github/workflows/pythonpackage.yml b/.github/workflows/pythonpackage.yml
--- a/.github/workflows/pythonpackage.yml
+++ b/.github/workflows/pythonpackage.yml
@@ -16,19 +16,48 @@ jobs:
       uses: actions/setup-python@v1
       with:
         python-version: ${{ matrix.python-version }}
+    - uses: ammaraskar/sphinx-action@master
+      with:
+        pre-build-command: "pip install -U sphinx ipython numpydoc sphinxcontrib-fulltoc sphinx-tabs sphinx_rtd_theme sphinx nbsphinx ipython pydata-sphinx-theme nbsphinx-link sphinx-panels"
+        docs-folder: "docs/"
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
     - name: Lint with flake8
       run: |
-        pip install flake8
+        pip install -U pytest coverage pytest-cov codecov black flake8
         # stop the build if there are Python syntax errors or undefined names
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+        black --check .
     - name: Test with pytest
       run: |
         pip install --editable .
         pip install pytest
         pytest
+        make coverage
+        codecov
+      # Publish built docs to gh-pages branch.
+    # ===============================
+    - name: Commit documentation changes
+      run: |
+        git clone https://github.com/saketkc/pysradb.git --branch gh-pages --single-branch gh-pages
+        cp -r docs/_build/html/* gh-pages/
+        cd gh-pages
+        touch .nojekyll
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # that.
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+    # ===============================
